"""Generate js/python-sources.js from attack_simulation.py and secure_solution.py.

The page shows the team's Python in its code panel (key K). Browsers refuse to
fetch() local files on a double-clicked page, so the sources are shipped as a
small generated script instead. Run this after editing either .py file:

    python3 tools/embed_python.py
"""
import json
import pathlib

root = pathlib.Path(__file__).resolve().parent.parent
names = ("attack_simulation", "secure_solution")
sources = {n: (root / f"{n}.py").read_text(encoding="utf-8").rstrip() + "\n" for n in names}

out = root / "js" / "python-sources.js"
out.write_text(
    "// Generated by tools/embed_python.py from "
    + " and ".join(f"{n}.py" for n in names)
    + ". Do not edit by hand.\n"
    + "window.PY_SOURCES = "
    + json.dumps(sources, indent=2, ensure_ascii=False)
    + ";\n",
    encoding="utf-8",
)
print(f"wrote {out.relative_to(root)}")
